/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penggajian;

import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author daksa
 */
public class frmjabatan extends javax.swing.JFrame {
    private boolean databaru;
    private Jabatan cl;

    /**
     * Creates new form frmjabatan
     */
    public frmjabatan() throws SQLException{
        initComponents();
        databaru = true;
        cl       = new Jabatan();
        GetData();
    }
    
    private void GetData()  throws SQLException
    {
        Object[] kolom = {"kode", "keterangan", "gapok", "tjabatan", "transport", "tmakan"};
        DefaultTableModel tabmode = new DefaultTableModel(null, kolom);
        ResultSet rs = cl.ViewByAll();
        while(rs.next())
        {
            String data[]={rs.getString("kodejabatan"),rs.getString("keterangan"),rs.getString("gapok"),rs.getString("tjabatan"), rs.getString("transport"), rs.getString("tmakan")};
            tabmode.addRow(data);
        }
        jTable1.setModel(tabmode);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtkd = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tjabatan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtransport = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tmakan = new javax.swing.JTextField();
        btntambah = new javax.swing.JButton();
        btnsimpan = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btnselesai = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtket = new javax.swing.JTextField();
        txtgp = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Form Jabatan");
        jLabel7.setToolTipText("");
        jLabel7.setOpaque(true);

        jLabel1.setText("Kode Jabatan");

        jLabel2.setText("Keterangan");

        jLabel3.setText("Gaji Pokok");

        jLabel4.setText("Tunjangan Jabatan");

        jLabel5.setText("Tunjangan Transport");

        jLabel6.setText("Tunjangan Makan");

        tmakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmakanActionPerformed(evt);
            }
        });

        btntambah.setText("Tambah");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });

        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        btnselesai.setText("Selesai");
        btnselesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnselesaiActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tmakan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addComponent(txtransport, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tjabatan)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btntambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnsimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnhapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnselesai))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtkd)
                            .addComponent(txtket)
                            .addComponent(txtgp, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtkd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtgp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tjabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtransport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tmakan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btntambah)
                            .addComponent(btnsimpan)
                            .addComponent(btnhapus)
                            .addComponent(btnselesai)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tmakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmakanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tmakanActionPerformed

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        // TODO add your handling code here:
        databaru = true;
        this.txtkd.setEditable(true);
        this.txtkd.setText("");
        this.txtket.setText("");
        this.txtgp.setText("");
        this.tjabatan.setText("");
        this.txtransport.setText("");
        this.tmakan.setText("");
        this.txtkd.grabFocus();
    }//GEN-LAST:event_btntambahActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        databaru = false;
        int row = jTable1.getSelectedRow();
        String tabel_klik =(jTable1.getModel().getValueAt(row, 0).toString());
        cl.setKd(tabel_klik);
        try
        {           
                ResultSet rs = cl.ViewById();
                if(rs.next())
                {
                    cl.setKd(rs.getString("kodejabatan"));
                    cl.setKet(rs.getString("keterangan"));
                    cl.setGp(Double.valueOf(rs.getString("gapok")));
                    cl.setJb(Double.valueOf(rs.getString("tjabatan")));
                    cl.setTransport(Double.valueOf(rs.getString("transport")));
                    cl.setMakan(Double.valueOf(rs.getString("tmakan")));
                    
                    this.txtkd.setText(cl.getKd());
                    this.txtket.setText(cl.getKet());
                    this.txtgp.setText(String.format("%.2f",cl.getGp()));
                    this.tjabatan.setText(String.format("%.2f",cl.getJb()));
                    this.txtransport.setText(String.format("%.2f",cl.getTransport()));
                    this.tmakan.setText(String.format("%.2f",cl.getMakan()));
                    this.txtkd.setEditable(false);
                }
        }catch(SQLException ex)
                {
                    Logger.getLogger(frmjabatan.class.getName()).log(Level.SEVERE, null, ex);
                }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnselesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnselesaiActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnselesaiActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
            cl.setKd(txtkd.getText());
            cl.setKet(txtket.getText());
            cl.setGp(Double.valueOf(txtgp.getText()));
            cl.setJb(Double.valueOf(tjabatan.getText()));
            cl.setTransport(Double.valueOf(txtransport.getText()));
            cl.setMakan(Double.valueOf(tmakan.getText()));
            boolean h = false;
            try
            {
                if(databaru == true)
                {
                    h = cl.Insert();
                }
                else
                {
                    h = cl.Update();
                }
                JOptionPane.showMessageDialog(null,"Penyimpanan berhasil");
                this.GetData();
                this.txtkd.setText("");
                this.txtket.setText("");
                this.txtgp.setText("");
                this.tjabatan.setText("");
                this.txtransport.setText("");
                this.tmakan.setText("");
                this.txtkd.grabFocus();
            } catch(SQLException ex)
            {
                JOptionPane.showMessageDialog(null, "Penyimpanan gagal" + ex.getMessage());
            }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        if("".equals(this.txtkd.getText()))
        {
            JOptionPane.showMessageDialog(null, "Silahkan klik pada grid untuk pilih data");
        }
        else
        {
            boolean h = false;
            try
            {
                cl.setKd(this.txtkd.getText());
                h = cl.Delete();
                JOptionPane.showMessageDialog(null, "Penghapusan data berhasil");
                GetData();
                this.txtkd.setText("");
                this.txtket.setText("");
                this.txtgp.setText("");
                this.tjabatan.setText("");
                this.txtransport.setText("");
                this.tmakan.setText("");
                this.txtkd.grabFocus();
               
            } catch(SQLException ex)
            {
                Logger.getLogger(frmjabatan.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmjabatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmjabatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmjabatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmjabatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new frmjabatan().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(frmjabatan.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnselesai;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btntambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tjabatan;
    private javax.swing.JTextField tmakan;
    private javax.swing.JTextField txtgp;
    private javax.swing.JTextField txtkd;
    private javax.swing.JTextField txtket;
    private javax.swing.JTextField txtransport;
    // End of variables declaration//GEN-END:variables
}
